from src.exceptions import new_exception

class GetFromDataBaseError(new_exception.NewException):
    pass